### ISSUE TITLE
Use internal packages

### ISSUE THREAD

**Issue by yaacov** [container-mgmt/messaging-library#18]
Do we want to use internal packages ?

Assigns to all :birthday:

**Comment by jhernand** [comment]
I do want :-) .

Everything that is not intended for direct use by the user of the library should be in internal packages, so that user can't actually use it.

**Comment by jhernand** [comment]
We should also consider using a mechanism similar to what is used by the Go `sql` package: a set of interfaces, and then a set of implementations that are selected on what package is imported.

**Comment by yaacov** [comment]
So we need a PR :-)

**Comment by yaacov** [comment]
@jhernand just to make clear (before I do it :-) )

we want to move:
"github.com/container-mgmt/messaging-library/pkg/client/connections/stomp"
to:
"github.com/container-mgmt/messaging-library/pkg/connections/stomp"
?

**Comment by jhernand** [comment]
I'd move it to `.../pkg/internal/stomp`.

**Comment by yaacov** [comment]
> I'd move it to .../pkg/internal/stomp.

On it :+1:

**Comment by yaacov** [comment]
I get:
```
use of internal package not allowed
```
when trying to use it :crying_cat_face: 
I do not think users we can access it if it's internal ?

**Comment by jhernand** [comment]
Exactly :-) ! That is what you want, the compiler forbidding you to use things that are internal.

**Comment by yaacov** [comment]
> Exactly :-) ! That is what you want, the compiler forbidding you to use things that are internal.

But I did want people to use it ! it's here for users to build their own implementations, and for us to show off our stomp as an example connection.

p.s.
OK, I will make it internal, but in return I want to remove the build script :-)
