### ISSUE TITLE
Supplying ContentType field in Message breaks Publish

### ISSUE THREAD

**Issue by nimrodshn** [container-mgmt/messaging-library#69]
e.g. a message like:
```
Message{
    ContentType:"application/json",
    Data:MessageData{
        "foo":"bar",
    }
}
Publish(m, "some-destination")
```
Does not get published. 

cc: @cben @yaacov

**Comment by cben** [comment]
do you know if not published, or not received?
not received by library or is it stomp-tool bug?

**Comment by nimrodshn** [comment]
The message is not received by the message-tool listening (i.e. running `./messaging-tool receive "some-destination"` doesn't receive the message (you've seen this with me yesterday..). I don't know the internals of the messaging library enough to say if it is by the library or the stomp-tool.

**Comment by yaacov** [comment]
Hi, thanks for the issue.

**a.** I assume you are using messeging-server [1] or artimis [2] as the messaging broker,
    do you see the some logging when sending and subscribing ?
**b.** `ContentType:"application/json",` is the default value of `ContentType`, you do not need to set it ...
**c.** `Publish(...)` return an error [3], do you get `nil` e.g. no error, or some error ?
**d.** when you publish using the `messaging-tool` [4] `send` command (and `messaging-server` [1]), do you see something new ?

[1] https://github.com/container-mgmt/messaging-library/tree/master/cmd/messaging-server
[2] https://github.com/container-mgmt/messaging-library/blob/master/.travis.yml#L22
[3] https://github.com/container-mgmt/messaging-library/blob/master/pkg/client/connection.go#L85
[4] https://github.com/container-mgmt/messaging-library/tree/master/cmd/messaging-tool

**Comment by nimrodshn** [comment]
> a. I assume you are using messeging-server [1] or artimis [2] as the messaging broker,
do you see the some logging when sending and subscribing ?
Using the messaging-server.
> b. ContentType:"application/json", is the default value of ContentType, you do not need to set it ...
Yeah your'e right still if someone needs to set it to some value...
> c. Publish(...) return an error [3], do you get nil e.g. no error, or some error ?
I didn't check the error on publish! I should fix that in the code...
d. when you publish using the messaging-tool [4] send command (and messaging-server [1]), do you see something new ?
Nope...

**Comment by yaacov** [comment]
>>   b. ContentType:"application/json", is the default value of ContentType, you do not need to set it ...

> Yeah your'e right still if someone needs to set it to some value...

Is their a problem with setting that value ?

does the publish work if you do not set it ?

>>    d. when you publish using the messaging-tool [4] send command (and messaging-server [1]), do you see something new ?

> Nope...

So the publish fails also in the examples, without any returned error ?

**Comment by nimrodshn** [comment]
Publish does work if I do not set.
Well in your're examples you do not set it...

**Comment by nimrodshn** [comment]
from what I saw [2] shouldn't seem to work..
I'll show you next week.

**Comment by yaacov** [comment]
but does it work ? you have a computer to check ?

**Comment by nimrodshn** [comment]
Works without `ContentType` (like your examples.)

**Comment by yaacov** [comment]
> Works without ContentType (like your examples.)

Great [1], and with `ContentType` like the the `messanging-tool` exmaple ?

[1]  you should not set it unless you send a `byteArray`

**Comment by yaacov** [comment]
Just checked it myself with `ContentType: contentType,` ... it works on my machine, did `git clone` `make` `make install`.

```
.gopath/bin/messaging-server serve
I0703 18:05:02.821805    5777 serve.go:71] Your friendly STOMP broker (YFSB) server 127.0.0.1:61613: [listen to all]
2018/07/03 18:06:15 connection closed: 127.0.0.1:50676
```

```
.gopath/bin/messaging-tool receive --destination="home"
I0703 18:05:54.068516    6245 receive.go:86] Connected to message broker at host 'localhost' and port 61613
I0703 18:05:54.068710    6245 receive.go:104] Subscribed to destination 'home' (Press Ctrl-C to exit)
I0703 18:06:15.824115    6245 receive.go:48] Received message from destination 'home':
map[kind:InfoMessage spec:map[message:hello]]
```

```
.gopath/bin/messaging-tool send --destination="home" --body="hello"
I0703 18:06:15.823361    6276 send.go:99] Connected to message broker at host 'localhost' and port 61613
I0703 18:06:15.823569    6276 send.go:136] Message: hello
I0703 18:06:15.823662    6276 send.go:163] Message sent

```

what do you get ?

**Comment by nimrodshn** [comment]
Well I tried it using the Publish API not the messaging tool cli.

> [1] you should not set it unless you send a byteArray

Also, you might want to document [1] - that might be the issue - I tried to pass an object to MessageData.

**Comment by yaacov** [comment]
> Well I tried it using the Publish API not the messaging tool cl

messaging tool is an example of using the Publish API that set the ContentType. so if it also works on your system, the API works with/or without setting the ContentType.

**Comment by yaacov** [comment]
> Also, you might want to document [1]

ContentType should match the payload you are sending, why do you want to changeit it if you are sending the default payload ?

**Comment by yaacov** [comment]
@nimrodshn we tested [1] that on the travis machine we can set  `ContentType` and message is sent ...

Can we close this issue ?
Can you find why on your system setting  `ContentType` fails ?

[1] https://github.com/container-mgmt/messaging-library/pull/71

**Comment by nimrodshn** [comment]
Tested now and it works. Closing issue.
